name: Test Duration Logger

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/min_requirements_pip.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies (pip)
        # TODO: once https://github.com/jerry-git/pytest-split/pull/10
        #   is merged, fix the custom pip install for pytest-split.
        run: |
          pip install wheel
          pip install -r requirements/min_requirements_pip.txt
          pip install git+https://github.com/ma-sadeghi/pytest-split.git@fix_ipynb_bug
          # Install porespy from the checked-out branch
          pip install -e . --no-deps

      - name: Running tests and examples
        run: |
          pytest \
            --nbval-lax examples/ \
            --store-durations \
            --durations-path test/fixtures/.test_durations_examples
          pytest \
            --store-durations \
            --durations-path test/fixtures/.test_durations_unittests

      - name: Committing test duration files
        uses: EndBug/add-and-commit@v7
        with:
          add: 'test/fixtures'
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Updated test duration files.'
